### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by neilmcdonald72** [Dynamsoft/capture-vision-react-native-samples#1]
Ran npm install and then tried to run npx react-native run-android but got this build error.

![image](https://user-images.githubusercontent.com/71236534/178262195-5ece688c-42d1-4056-89be-f5bbfaa9744b.png)

**Comment by Dynamsoft-Jerson** [comment]
@neilmcdonald72 
It seems to be a network issue. Is it ok now?
