### ISSUE TITLE
undefined DynamsoftCameraView

### ISSUE THREAD

**Issue by JmarshTri** [Dynamsoft/capture-vision-react-native-samples#2]
When opening my barcode scanner file with this code I'm getting undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[9], "dynamsoft-capture-vision-react-native").DynamsoftCameraView'). I added the package via yarn and no matter what I do I keep getting this error

**Comment by coheedandcambria** [comment]
Hello and thank you for contacting us,

In your App.js file, is the DynamsoftCameraView component imported from the 'dynamsoft-capture-vision-react-native' library? if you are not sure what I am referring to, please go through our user guide: https://www.dynamsoft.com/capture-vision/docs/programming/react-native/user-guide/barcode-reader.html?ver=latest

**Comment by Dynamsoft-Jerson** [comment]
@JmarshTri 
Hi, did you solve this problem?

**Comment by Dynamsoft-Jerson** [comment]
We can't repro.
