### ISSUE TITLE
DCVCameraView does appear in screen if user taps back button to go to Home screen and locks phone

### ISSUE THREAD

**Issue by chernandez-bunnings** [Dynamsoft/capture-vision-react-native-samples#3]
<img src="https://user-images.githubusercontent.com/106944724/194800436-f11ef641-a05e-49a1-8455-14f5b69ba6ff.png" width="400"/>

We are currently evaluating `Dynamsoft Capture Vision SDK` and this issue occurs in our internal implementation as well as in this sample application.

### Current Behavior:
Camera won't appear when user has gone back to _Home_ page from _Scanner_ screen and has locked the phone (or the phone has gone to sleep). The point being the app has been flagged as a background process in the device.  

### Expected Behavior:
Camera to display correctly when bringing process from background to foreground and navigating from Home to Scanner screen.

### Steps To Reproduce:

Create fresh install and compile the app in both platforms.

Example: steps to reproduce the behaviour:
1. Open the app
2. Tap on "Start scanning" button
3. Accept permissions request
4. Camera screen displays correctly 
5. Tap on back button to go to Home screen
6. In the home screen, lock phone, or ensure the phone goes to sleep
7. Unlock phone, to resume from background
8. Tap on "Start scanning" button
9. Camera screen does not display correctly

> __Note__: Locking screen/setting phone to sleep in Scanner screen and unlocking it, will trigger the Camera to be remounted and it will display correctly.

### Environment:
This issue occurs in Android and iOS.

**Comment by Dynamsoft-Jerson** [comment]
Hi, thank you for contacting us, our team is reviewing this issue.

**Comment by Dynamsoft-Jerson** [comment]
@chernandez-bunnings 
We have found this bug and will fix it in the next release.

**Comment by chernandez-bunnings** [comment]
@Dynamsoft-Jerson thank for looking into it. We will be attentive to the new release :)

**Comment by Dynamsoft-Jerson** [comment]
@chernandez-bunnings A new version has been released. Please try it. :)

**Comment by chernandez-bunnings** [comment]
@Dynamsoft-Jerson good news, we tested `dynamsoft-capture-vision-react-native` version: `1.1.7` and it works in both `android` and `ios` 🎆. Thank you :)
